/// Applies the platform patch tree in `patches/` over the working tree.
///
/// Files under `macos/` and `windows/` are generated by `flutter create`
/// and are silently reverted whenever the platform folders are
/// regenerated, taking hand-made edits (the window_manager Quit override,
/// the release entitlements) with them. `patches/` holds the authoritative
/// copy of every such file so a release build can restore them before
/// compiling.
///
/// Layout: `patches/<platform>/<path relative to the repo root>`. The
/// platform segment selects which patches a build applies; the rest is the
/// destination path verbatim. So the macOS AppDelegate lives at
/// `patches/macos/macos/Runner/AppDelegate.swift` — the first `macos` is
/// the platform bucket, the second is the real directory it lands in.
/// Nesting the full repo-relative path (rather than a path relative to the
/// platform folder) means a patch can target a file anywhere in the repo,
/// not just inside `macos/` or `windows/`.
///
/// Run standalone with
/// `dart run scripts/release/apply_patches.dart macos` (or `windows`);
/// the build scripts call [applyPatches] directly.
library;

import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;

import 'common.dart';

Future<void> main(List<String> args) => runScript(() async {
  if (args.length != 1 || !const ['macos', 'windows'].contains(args.single)) {
    throw ReleaseException(
      'Usage: dart run scripts/release/apply_patches.dart <macos|windows>',
    );
  }
  applyPatches(args.single);
});

/// Copies every patch for [platform] over its destination, skipping files
/// whose contents already match.
///
/// An absent `patches/<platform>/` directory is not an error: a platform
/// with nothing to patch simply has no bucket.
void applyPatches(String platform) {
  step('Applying $platform patches');

  final patchRoot = Directory(p.join(repoRoot, 'patches', platform));
  if (!patchRoot.existsSync()) {
    stdout.writeln('No patches/$platform directory; nothing to apply.');
    return;
  }

  final patches =
      patchRoot
          .listSync(recursive: true)
          .whereType<File>()
          // Directory metadata, not patch content: copying these would
          // scatter stray .DS_Store/.gitkeep files across the repo.
          .where(
            (file) => !const [
              '.DS_Store',
              '.gitkeep',
            ].contains(p.basename(file.path)),
          )
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  if (patches.isEmpty) {
    stdout.writeln('patches/$platform is empty; nothing to apply.');
    return;
  }

  var applied = 0;
  var skipped = 0;
  for (final patch in patches) {
    final relativePath = p.relative(patch.path, from: patchRoot.path);
    final target = File(p.join(repoRoot, relativePath));

    if (target.existsSync() && _sameContents(patch, target)) {
      stdout.writeln('  ${'skipped (identical)'.padRight(20)}$relativePath');
      skipped++;
      continue;
    }

    // 'restored' distinguishes a file the platform folder lost entirely
    // from one that merely drifted, which is the more alarming case.
    final verb = target.existsSync() ? 'patched' : 'restored (missing)';
    target.parent.createSync(recursive: true);
    patch.copySync(target.path);
    stdout.writeln('  ${verb.padRight(20)}$relativePath');
    applied++;
  }

  stdout.writeln(
    '$applied applied, $skipped already up to date '
    '(${patches.length} patch${patches.length == 1 ? '' : 'es'}).',
  );
}

/// Whether two files are byte-identical, compared by SHA-256.
bool _sameContents(File a, File b) =>
    sha256.convert(a.readAsBytesSync()) == sha256.convert(b.readAsBytesSync());
