enum PropertyDeltaName {
  none,
  name,
  cableLength,
  permanentComposition,
  loomType,
  loomClass,
  isDrop,
  hasVariedLengthChildren,
  notes,
  cableType,
  isSpare,
  delimiter,
  multiPrefix,
  color,
  label,
  locationId,
  isExtension,
  fixtureId,
  fixtureType,
  universe,
  address, loomId, outletId, parentMultiId, loomLength, locationName, multiCount, multiName, desiredSpareCircuits, patchedFixtureIds, load,
}

enum DiffState {
  unchanged,
  added,
  changed,
  deleted,
}
